WITH CALENDAR_OF_WORK_DATES AS ( 
    SELECT 
            *, 
            DENSE_RANK() OVER (PARTITION BY DOCUMENT_DT ORDER BY CALENDAR_DATE  ASC) drnk
    FROM 
            MESSAGE
    JOIN 
            CALENDAR ON DOCUMENT_DT <= CALENDAR_DATE
    WHERE 
            IS_DAYOFF = 1
 )

 
SELECT
    T1_MESSAGE.DOCUMENT_ID as doc_id
FROM 
    MESSAGE T1_MESSAGE  
INNER JOIN 
    (
        SELECT 
            DOCUMENT_ID AS CHILD_DOCUMENT_ID, 
            DOCUMENT_DT AS ANSWER_DT
        FROM
            MESSAGE
  ) T2_MESSAGE 
ON 
      T1_MESSAGE.CHILD_DOCUMENT_ID  = T2_MESSAGE.CHILD_DOCUMENT_ID
LEFT  JOIN 
    (
        SELECT DISTINCT
            DOCUMENT_DT, 
            CALENDAR_DATE AS FIFTH_WORK_DATE
        FROM 
            CALENDAR_OF_WORK_DATES
        WHERE 
            drnk = 5
  )  FIFTH_WORK_DATES
ON 
        T1_MESSAGE.DOCUMENT_DT  = FIFTH_WORK_DATES.DOCUMENT_DT
WHERE      
        T2_MESSAGE.ANSWER_DT > FIFTH_WORK_DATES.FIFTH_WORK_DATE
